### ISSUE TITLE
Deprecated nuget packages (Enigmatry.Entry.GraphApi)

### ISSUE THREAD

**Issue by cvetanstoimenov** [enigmatry/entry-building-blocks#69]
While doing security scan for another project, I found 2 deprecated nuget packages in Enigmatry.Entry.GraphApi.

Deprecated nuget packages:
- Microsoft.IdentityModel.JsonWebTokens (6.24.0)
- System.IdentityModel.Tokens.Jwt (6.24.0)

**Comment by avanwaas** [comment]
Solved in https://github.com/enigmatry/entry-building-blocks/pull/74
